Repository newyorkmyc/keys-typeahead, pull requests merged in 2024-10, with the labels that each got.

#2 Add tooling
  .commitlintrc.json
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  .lintstagedrc
  package.json
  pnpm-lock.yaml
Labels: documentation, enhancement

#7 5 all contributors bot
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#10 Create LICENSE.MD
  LICENSE.MD
Labels: documentation

#4 Create README.md
  .all-contributorsrc
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  README.md
  package-lock.json
  package.json
Labels: documentation

#11 build: include mycetozoa
  .husky/pre-commit
  create_json_taxonomy.py
  fungi_taxonomy.json
  typahead_genera.html
Labels: enhancement
